services:
  - type: web
    name: safemate-care
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0